/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  int[] test1 = new int[]{1};
  int[] test2 = new int[]{1, 2};
  int[] test3 = new int[]{1, 2, 3};

  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  public void testEmpty() {
    LinkedList sut = new LinkedList();
    assertTrue(sut.getList() == null, "should be true");
  }

  @Test
  public void testInsert() {
    LinkedList sut = new LinkedList();
    sut.insert(test1[0]);
    assert (sut.getList().getData() == 1);
  }

  @Test
  public void testHead() {
    LinkedList sut = new LinkedList();
    int i = 0;

    while (i < test2.length) {
      sut.insert(test2[i]);
      ++i;
    }
    assert (sut.getList().getData() == 2);
  }


  @Test
  public void testTail() {
    LinkedList sut = new LinkedList();
    int i = 0;

    while (i < test2.length) {
      sut.insert(test2[i]);
      ++i;
    }
    assert (sut.getList().getNext().getData() == 1);
  }

  @Test
  public void trueTestIncludes()
  {
    LinkedList sut = new LinkedList();
    int i = 0;
    while (i < test3.length) {
      sut.insert(test3[i]);
      ++i;
    }
    //assert(sut.includes(2));
    assertTrue(sut.includes(2), "assert 2 exists");
  }

  @Test
  public void falseTestIncludes()
  {
    LinkedList sut = new LinkedList();
    int i = 0;
    while (i < test3.length) {
      sut.insert(test3[i]);
      ++i;
    }

    assertTrue(!sut.includes(5), "assert 5 exists");
    return;
  }

  @Test
  public void testDisplay()
  {
    LinkedList sut = new LinkedList();
    int i = 0;
    while (i < test3.length) {
      sut.insert(test3[i]);
      ++i;
    }
    assert(sut.toString().equals("{3} -> {2} -> {1} -> NULL"));
  }

}
