/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
       new App().run();
    }
    public void run()
    {
      LinkedList list = null;
      int [] array = new int[]{1,2,3,4};
      for(int i = 0; i < array.length; ++i) {
        list = new LinkedList(array[i]);
      }

      System.out.println(list.toString());
      return;
    }
}
