name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install cmake libgtest-dev

    - name: Build project
      run: |
        cmake -S . -B build
        cmake --build build
      working-directory: ./cplusplus

    - name: Verify Build directory
      run: ls -l cplusplus

    - name: Run tests
      run: |
        ls -a ../build/
        cd ${{github.workspace}}/cplusplus/build
        ctest -V
      working-directory: ./cplusplus/Google_tests
