name: Run .Net Tests

on:
  push:
    branches: [main]
    paths:
      - 'c-sharp/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/dotnet.Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'c-sharp/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/dotnet.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and test .NET
        run: docker compose run --rm dotnet
