name: Run Java Tests

on:
  push:
    branches: [main]
    paths:
      - 'java/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/java.Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'java/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/java.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and test Java
        run: docker compose run --rm java
