name: Run Javascript Tests

on:
  push:
    branches: [main]
    paths:
      - 'javascript/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/javascript.Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'javascript/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/javascript.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and test JavaScript
        run: docker compose run --rm javascript
