name: Run Python Tests

on:
  push:
    branches: [main]
    paths:
      - 'python/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/python.Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'python/**'
      - 'compose.yml'
      - '.dockerignore'
      - 'docker/python.Dockerfile'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Python
        run: docker compose run --rm python
